#!/bin/sh

echo -e -n "Content-type: text/html;charset=utf-8\n\n";
echo -e -n "<!DOCTYPE html>"

echo -e -n "<html lang=en>"
echo -e -n "<head>"
echo -e -n "<title>aawordsearch | Generated word search puzzle</title>"
echo -e -n "</head>"

echo -e -n "<body>"
echo -e -n "<pre>"
./aawordsearch --lang=it -V
echo -e -n "</pre>"

echo -e -n "<p>Generated by <a href=\"https://github.com/theimpossibleastronaut/aawordsearch\">aawordsearch</a></p>"
echo -e -n "<p><a href=\"/\">Home</a></p>"

echo -e -n "</body>"
echo -e -n "</html>"
