name: C/C++ CI
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ trunk ]
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/codeql-analysis.yml'
  pull_request:
    branches: [ trunk ]
    paths-ignore:
    - '**/*.md'
    - '.github/workflows/codeql-analysis.yml'

jobs:
  Ubuntu:
    strategy:
      matrix:
        curl: [true, false]
    runs-on: ubuntu-latest
    env:
      MATRIX_CURL: ${{ matrix.curl }}
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo apt-get install -y meson valgrind
        if [ "$MATRIX_CURL" = "true" ]; then
          sudo apt-get install -y  libcurl4-openssl-dev
        fi
    - name: Configure, Build, and Test
      run: |
        meson setup _build
        cd _build
        ninja -v
        meson test
        meson test --setup=valgrind

  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        brew install meson
    - run: |
        meson _build
        cd _build
        ninja -v
        ninja test
